name: Test Code
on: [push]

jobs:
  build:
    runs-on: 'windows-latest'
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with: 
          python-version: 3.8
      - name: Install build deps
        run: |
          python -m pip install -r requirements.txt
      - name: Test
        run: python src/robot.py test